### PR TITLE
Added google search metadata and a sitemap

### PR DESCRIPTION
**Pull request by wadleo**
Hi @Ch3ck 
I have added what's necessary for google to index the site in its searches can you deployed this lets see if more is needed, thanks.

### CODE REVIEW

**Comment by ch3ck** [comment]
Squash these commits into one. The merge commit is just an empty commit @wadleo Fix that. I'll merge and  @tahteche could deploy

**Comment by ch3ck** [comment]
This looks better now.

**Comment by wadleo** [comment]
Have the changes been deployed? So can evaluate the work done here and add the sitemap on the google search console.

**Comment by tahteche** [comment]
It's deployed

**Comment by bosz** [comment]
Great. Kodos

**Pull request merged**
